version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: pepe22
      MYSQL_DATABASE: app
      MYSQL_PASSWORD: pepe22
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - springboot-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: pepe22
    depends_on:
      - mysql
    ports:
      - "8081:80"
    networks:
      - springboot-network

  app:
    image: api
    container_name: spring_app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/app?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: pepe22
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    networks:
      - springboot-network

volumes:
  mysql_data:

networks:
  springboot-network:
    driver: bridge
